### ISSUE TITLE
Hotspot is broken on Evolution X 4.4

### ISSUE THREAD

**Issue by xmine64** [chips-project/msm-4.14#1]

**Comment by najahiiii** [comment]
fixed already. will be pushed into ci channel soon.

**Comment by najahiiii** [comment]
> fixed already. will be pushed into ci channel soon.

You can use this build artifact here. https://github.com/chips-project/msm-4.14/actions/runs/161533514 download it and extract it and then flash

**Comment by xmine64** [comment]
5GHz still not working

**Comment by najahiiii** [comment]
> 5Hz still not working

I'll look into it. 

never notice that, coz never use that

**Comment by xmine64** [comment]
> > 5Hz still not working
> 
> I'll look into it.
> 
> never notice that, coz never use that

Me, too
I just wanted to test is it perfect or not

**Comment by najahiiii** [comment]
> > > 5Hz still not working
> > 
> > 
> > I'll look into it.
> > never notice that, coz never use that
> 
> Me, too
> I just wanted to test is it perfect or not

5GHz only work if your router supports 5GHz bandwidth. so, check your router AP. if your router support it. then 5GHz will work properly.
beside, I don't have any WiFi AP with 5GHz bw. So I can't check the WiFi.

**Comment by xmine64** [comment]
I mean I can't start a hotspot with 5GHz bandwidth. It gets disable automatically right after enabling it.

![Screenshot_20200713-123638484.jpg](https://user-images.githubusercontent.com/21140798/87279548-ca5c0200-c4df-11ea-8b30-b484f1e19ebd.jpg)

**Comment by najahiiii** [comment]
> I mean I can't start a hotspot with 5GHz bandwidth. It gets disable automatically right after enabling it.
> 
> ![Screenshot_20200713-123638484.jpg](https://user-images.githubusercontent.com/21140798/87279548-ca5c0200-c4df-11ea-8b30-b484f1e19ebd.jpg)

I have a new test build for you. just contact me in [telegram](https://t.me/najahiii) if you want to test.

tested fine in MIUI EU v20.7.9

**Comment by xmine64** [comment]
Thanks, I don't use 5GHz, I just wanted to let you know, to make it perfect, I'll wait until stable.

**Comment by najahiiii** [comment]
> Thanks, I don't use 5GHz, I just wanted to let you know, to make it perfect, I'll wait until stable.

Just checked. tested tethering using 5GHz and working fine. Internet connection in client side is working fine.
