### ISSUE TITLE
Slowmotion camera doesn't work

### ISSUE THREAD

**Issue by xmine64** [chips-project/msm-4.14#2]
I tried ANXCamera v182, v184, v185 on Evolution X, and Xiaomi EU MIUI 12.
Camera app freezes on slowmotion mode.
It works on other kernels.

**Comment by najahiiii** [comment]
Added to bug list, I'll look into it.

**Comment by xmine64** [comment]
I tried again and slowmotion is working even better than stock kernel. I don't know why I opened this issue, sorry.
